### PR TITLE
CS732-37 add getlolocation picker, fix malformat openhour

### PR DESCRIPTION
**Pull request by KevinHChen**
1. Allow getting geolocation picker
1. Fix malformatted openhour

image

image

### CODE REVIEW

**Comment by MarkZhuVUW** [comment]
does this get user location or ec2 location?

**Comment by KevinHChen** [comment]
It gets browser location of course

**Comment by MarkZhuVUW** [comment]
> It gets browser location of course

does not seem working

**Comment by MarkZhuVUW** [comment]
> You should grant your browser location permission
can we include this in readme Q&A?

**Comment by KevinHChen** [comment]
No need. All location picker, google's, microsoft's work in the same way. It's a chrome/edge build-in feature, and it's not our responsibility to educate users.

**Review by MarkZhuVUW — APPROVED** [review]

**Pull request merged**
