### PR TITLE
CS732-34 redo landing page

### PR DESCRIPTION
**Pull request by KevinHChen**
Redo the landing page

image

### CODE REVIEW

**Comment by MarkZhuVUW** [comment]
> Redo the landing page
> 
> image

looks good. Can we verify that this works on EC2 and responsive design is good if you have not done it already?

Thanks

**Comment by KevinHChen** [comment]
looks good now
image
image

**Comment by KevinHChen** [comment]
BTW, the landing page can't fit both mobile and PC unless exact work is done, as I set different length to different Card there to make it not boring

**Review by MarkZhuVUW — APPROVED** [review]

**Comment by MarkZhuVUW** [comment]
> BTW, the landing page can't fit both mobile and PC unless extra work is done, as I set different length to different Card there to make it not boring

on mobile view you can simply display them horizontally, similar to how comments, vote results are displayed

**Pull request merged**
